### ISSUE TITLE
SHEBANG!

### ISSUE THREAD

**Issue by Itsfoss0** [Michelle-Wanderi/AirBnB_clone#4]
I've noticed that [some of the scripts](https://github.com/Michelle-Wanderi/AirBnB_clone/blob/master/models/base_model.py) Don't begin with a shebang line. Will that be an issue as the project requirements on the intranet suggests that all scripts begin with a ```#!/usr/bin/python3```? 

![image](https://user-images.githubusercontent.com/105123601/217633998-3eed4d61-c17b-4a35-a4e9-9d8ae97ab63b.png)

**Comment by Michelle-Wanderi** [comment]
I'm not so sure. But for the console I'm sure it has to have the shebang because we are executing it
 About the others I'm not sure
