### ISSUE TITLE
CONSOLE

### ISSUE THREAD

**Issue by Itsfoss0** [Michelle-Wanderi/AirBnB_clone#5]
Develop the console to manage creation, representation and deletion of objects. With the following commands. 
- ```create```
- ```show```
- ```destroy```
- ```all```
- ```update```

**Comment by Itsfoss0** [comment]
Assign this to me.

**Comment by Michelle-Wanderi** [comment]
Okay

**Comment by Michelle-Wanderi** [comment]
I think its okay?

**Comment by Itsfoss0** [comment]
Yeah Yeah. 
That's fine.
