### ISSUE TITLE
TEST 

### ISSUE THREAD

**Issue by Itsfoss0** [Michelle-Wanderi/AirBnB_clone#8]
Hi @Michelle-Wanderi 
We need to add test suites for the BaseModel and FileStorage classes.

**Comment by Itsfoss0** [comment]
Some of the tests are covered in [this](https://github.com/Michelle-Wanderi/AirBnB_clone/pull/7) Pull Request. 
I'll keep working on the rest.

**Comment by Michelle-Wanderi** [comment]
Very conmendable changes. I will review all of them

**Comment by Michelle-Wanderi** [comment]
Everything is ok

**Comment by Michelle-Wanderi** [comment]
Okay

**Comment by Michelle-Wanderi** [comment]
Everything is okay
